# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Defrag
version:      0.03
version_from: Defrag.pm
installdirs:  site
requires:
    Sys::FreezeThaw:               0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
